#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from pathlib import Path

BASE_VERSION = "0.1.0-mf3-persist1"


def patch(root: Path, git_sha: str) -> None:
    short = re.sub(r"[^0-9a-fA-F]", "", git_sha)[:8].lower()
    if len(short) != 8:
        raise SystemExit(f"invalid git SHA for MF3 identity: {git_sha!r}")
    version = f"{BASE_VERSION}+g{short}"

    header = root / "include/ursus_version.h"
    scm = root / ".scmversion"
    if not header.is_file() or not scm.is_file():
        raise SystemExit("missing Ursus version inputs")

    text = header.read_text(encoding="utf-8")
    out, count = re.subn(
        r'#define URSUS_VERSION "[^"]+"',
        f'#define URSUS_VERSION "{version}"',
        text,
        count=1,
    )
    if count != 1:
        raise SystemExit(f"URSUS_VERSION replacement count={count}")
    header.write_text(out, encoding="utf-8")
    scm.write_text(f"-UrsusBoot-{version}\n", encoding="utf-8")

    marker = root / "include/ursus_mf3_persist_identity.h"
    marker.write_text(
        "/* generated by mf3_persist_identity.py */\n"
        f'#define URSUS_MF3_GIT_SHA "{git_sha}"\n'
        f'#define URSUS_MF3_VERSION "{version}"\n'
        '#define URSUS_MF3_WRITE_SCOPE "FIP_ONLY_CANARY"\n',
        encoding="utf-8",
    )
    print(f"MF3_PERSIST_IDENTITY=PASS version={version} scope=FIP_ONLY_CANARY")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("source_root", type=Path)
    ap.add_argument("git_sha")
    args = ap.parse_args()
    patch(args.source_root.resolve(), args.git_sha)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
